spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: changeYourPassword
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8090
#logging:
#  level:
#    org.virayer.sqlcompletion.dao: debug